### PR TITLE
Multi module

### PR DESCRIPTION
**Pull request by Osaigbovo**
**What this PR does**:
Modularisation of the codebase to a multi-module app.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:

**Additional comments**:

### CODE REVIEW

**Comment by mayorJAY** [comment]
@Osaigbovo Great job but there are quite a number of unresolved conflicts which probably also didn't allow the CI checks to run. Kindly see to these

**Review by mayorjay — COMMENTED** [review]
@Osaigbovo Great job but there are quite a number of unresolved conflicts which probably also didn't allow the CI checks to run. Kindly see to these

**Comment by latnok25** [comment]
Hi did this PR pass any CI checks are they any errors or conflicts that need to be resolved

**Comment by Osaigbovo** [comment]
Hello! The conflicts were expected because I did a complete restructuring of the base code. Most of the codes were either deleted, given appropriate names or moved to the appropriate module. We expect this will serve as our foundation for future work and collaboration. Thanks

**Comment by latnok25** [comment]
Hi @Osaigbovo if this is the foundation for the future which module houses reusable components or do we create a new module for components because most of them are going to be used across different modules

**Comment by Osaigbovo** [comment]
Hello! That will be the core module. The core module will have all the core resources and reusable objects...

**Review by FreedomChuks — APPROVED** [review]

**Review by bhavinmdesai — APPROVED** [review]

**Pull request merged**
