### PR TITLE
updated strings for home module

### PR DESCRIPTION
**Pull request by mbobiosio**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:

**Additional comments**:

### CODE REVIEW

**Comment by tejasm2** [comment]
Hey @mbobiosio can you please also add the screenshots related to both the PRs you created?

**Review by mayorjay — COMMENTED** [review]
Hi @mbobiosio this looks good to me but kindly add a Screenshot whenever you're opening a PR. Thanks

**Review by mayorjay — APPROVED** [review]

**Comment by mayorjay** [comment]
Hey @tejasm2 @carl05 @Osaigbovo kindly review this PR so that it can be merged as soon as possible. Thanks

**Review by Osaigbovo — APPROVED** [review]

**Pull request merged**
