### PR TITLE
New mvvm arch

### PR DESCRIPTION
**Pull request by mayorjay**
**What this PR does**:
This PR contains the new MVVM architecture

### CODE REVIEW

**Comment by bhavinmdesai** [comment]
@mayorJAY Can you have a look at Detekt errors? Ignore the "empty block" ones but there are few other errors like new line etc.

**Comment by FreedomChuks** [comment]
fix raised issue and lint checks

**Comment by latnok25** [comment]
HI @mayorJAY can you look at detekt errors and provide a solution or explain why it's generating those errors?
thanks.

**Comment by mayorjay** [comment]
@bhavinmdesai @gzodx @latnok25 The detekt errors basically are of 3 types:
i. Empty class or empty method blocks (EmptyClassBlock/EmptyFunctionBlock)
ii. New line needed at the end of each file (NewLineAtEndOfFile/FinalNewline)
iii. Other types such as NoBlankLineBeforeRbrace, SpacingAroundComma, etc
As @bhavinmdesai mentioned, (i) can be ignored; I fixed (ii) already but I discovered that Detekt keeps flagging those same files as not having a new line at the end
**But note that with those errors fixed or not, the App works just fine.** I have also observed that quite a number of other PRs have been merged even though the detekt check fails as long as the checks to **Generate APK** and that of **Travis CI** passes
Thanks

**Comment by FreedomChuks** [comment]
True but Let follow the best practices as possible and let try to make sure our pr pass the lint checks 

Having Todo () could also potentially crash the app too kindly replace it with //Todo stating your intended implementation cheers 👍

**Comment by latnok25** [comment]
@mayorJAY no major errors from the lint checks but the as @gzodx said it's good to use best PR practices.

LGTM from my end but handle the TODO and lint checks

**Comment by mayorjay** [comment]
@tejasm2 @bhavinmdesai @latnok25

**Review by bhavinmdesai — APPROVED** [review]

**Review by latnok25 — APPROVED** [review]
LGTM klint error has been taken cared of

**Pull request merged**
