### PR TITLE
Profile xml

### PR DESCRIPTION
**Pull request by jaliquiel**
**What this PR does**:
XML file for the signed out profile. https://app.zeplin.io/project/5ec4729feee8e847b8d9f1d1/screen/5f1cee3fbe507742899aff7b

**Which issue(s) this PR fixes**:
Part of Profile: View Profile # 93
Fixes #

**Special notes for reviewers**:

**Additional comments**:

### CODE REVIEW

**Comment by jaliquiel** [comment]
I get these warnings related to the svg file, is this fine?
image

**Comment by Osaigbovo** [comment]
It is okay. I will look at it properly

**Review by Osaigbovo — APPROVED** [review]

**Review by mayorjay — COMMENTED** [review]
@jaliquiel Kindly add a Screenshot to show the XML looks like on a device. Thanks

**Comment by jaliquiel** [comment]
Here is a screenshot of the xml for a Pixel: 
image

**Review by mayorjay — APPROVED** [review]

**Pull request merged**
