### PR TITLE
added more profile xml

### LINKED ISSUE #69: Milestone: Edit Individual Profile
Edit Individual Profile UI: https://app.zeplin.io/project/5ec4729feee8e847b8d9f1d1?seid=5f1bb84a4d6257373f7c0659

As a logged in user,
Given that I am on the Feed and I tap 'My Profile', 
Then I should be presented with the 'My Profile' page with several options to navigate to 'Name', 'Add Social Media links', and 'About Me' as well as Profile picture, and edit icon on Profile Picture.

image

Given I am on the 'My Profile' page

When I tap on the "Edit icon" next to Profile image,
Then the image selection/editing page will load (need to find design on Zeplin).

When I tap on the "Name" navbar,
Then I should be led to a page to edit my Name

image

When I tap on the "Add Social Media Links" navbar
Then I should be led to a page to add the links to my social media profiles

image

When I tap on the "About Me" navbar
Then I should be led to a page to fill in text about myself.

image

Acceptance Criteria:
User is successfully able to navigate to the respective pages required to edit their individual profile.

### PR DESCRIPTION
**Pull request by mbobiosio**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for reviewers**:

**Additional comments**:

### CODE REVIEW

**Comment by mbobiosio** [comment]
Screenshot from 2020-09-23 15-34-19
Screenshot from 2020-09-23 15-34-42
Screenshot from 2020-09-23 15-35-19

**Review by mayorjay — COMMENTED** [review]
Looks good to me. Just the CI checks that don't seem to pass

**Comment by mbobiosio** [comment]
Screenshot from 2020-09-25 11-21-43
This is a preview from AS Layout Preview

**Review by mayorjay — APPROVED** [review]

**Comment by mayorjay** [comment]
Hey @tejasm2 @carl05 @Osaigbovo kindly review this PR so that it can be merged as soon as possible. Thanks

**Comment by Osaigbovo** [comment]
Hello Obi, please you will have to use Fragments instead of Activities for those screens. Thanks.

**Comment by mbobiosio** [comment]
Hello @Osaigbovo how are those Fragments? Maybe I missed the Architecture flow?

**Comment by Osaigbovo** [comment]
Can I call you to explain?

**Review by carl05 — APPROVED** [review]

**Pull request merged**
